[package]
name = "simple-app"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wgpu = "0.17"
futures = "0.3"
winit = "0.28"
env_logger ="0.11.3"
bytemuck = { version = "1.4", features = ["derive"] }
pollster = "0.3"